version: '3'
services:
    lms_api:
        container_name: lms_api
        build:
            context: ./docker/
            dockerfile: laravel.Dockerfile
        volumes:
            - ./:/usr/share/nginx/html:cached
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - lms_db
            - lms_redis
            - lms_mailpit
        ports:
            - "5173:5173"
        env_file:
            - ./docker/env.dev.yml
        restart: always
        tty: true
        privileged: true

    http-nginx:
        image: nginx:alpine
        container_name: lms_nginx
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./docker/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./:/usr/share/nginx/html:cached
            - ./docker/cert:/etc/nginx/cert
            - ./docker/hosts:/etc/hosts:cached
        links:
            - lms_api
            - lms_db
            - lms_redis
            - lms_mailpit
        restart: always

    lms_db:
        container_name: lms_db
        image: mysql:8.0
        ports:
            - "33006:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        restart: always
        volumes:
            - ./docker:/etc/mysql/conf.d
            - ./docker/initdb:/docker-entrypoint-initdb.d
            - ./docker/mysql-data:/var/lib/mysql

    lms_adminer:
        container_name: lms_adminer
        image: adminer:latest
        environment:
            ADMINER_DEFAULT_SERVER: lms_db
        restart: always
        ports:
            - "28310:8080"

    lms_redis:
        image: redis:alpine
        container_name: lms_redis
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - ./docker/redis:/data
        ports:
            - "8002:6379"
        restart: always
    lms_mailpit:
        container_name: lms_mailpit
        image: axllent/mailpit:latest
        restart: unless-stopped
        ports:
            - "1025:1025"
            - "8025:8025"
